### ISSUE TITLE
missing instructions

### ISSUE THREAD

**Issue by dilawar** [PotHix/Vimpress#3]
The documentation is lacking a bit (original script does not have an existing project page with instructions).

Can you add couple of line where the config file should go and what it is named? 

Thanks for maintaining the project. I remember it using it long time back. Currently I am struggling with vim-8; but  not sure if I am putting the right values in config file.

**Comment by PotHix** [comment]
Unfortunately, I'm not using Wordpress for a long time now, so I'm not maintaining this plugin anymore. But it should be really straightforward to use.

IIRC, you should have this file in your $HOME https://github.com/PotHix/pothix-dotfiles/blob/master/modules/editor/vim/plugins/vimpress/dist/.vimpressrc

And just install it using pathogen (or Vundle, maybe). My last commit was almost 6 years ago. :)
